name: Package Application with Pyinstaller

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: mathlibtools

    - uses: actions/upload-artifact@v2
      with:
        name: leanproject.exe
        path: mathlibtools
        spec: leanproject.spec
