name: Package Application with Pyinstaller

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install pyinstaller
      run: python -m pip install pyinstaller -r mathlibtools/pyinstaller-requirements.txt

    - name: Run pyinstaller
      run: python -m PyInstaller mathlibtools/leanproject.spec

    - name: Check the resulting exe functions
      run: ${{ github.workspace }}/dist/leanprojectTESTTOBREAK.exe --help

    - uses: actions/upload-artifact@v2
      with:
        name: leanproject.exe
        path: dist/
