name: Package Application with Pyinstaller

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: mathlibtools
        spec: leanproject.spec
        requirements: pyinstaller-requirements.txt
      
    - name: Test .exe file
      run: mathlibtools\dist\windows\leanproject.exe --help

    - uses: actions/upload-artifact@v2
      with:
        name: leanproject.exe
        path: mathlibtools/dist/windows
